name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run Tests
        run: go test
      - name: Run App
        run: go run math.go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: andsas/fc2.0-ci-go:latest